WebInterface/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager
from sqlalchemy import true
from Server.utils import append_parent_dir
from datetime import timedelta

append_parent_dir()

from privates import *



db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = APP_SECRET_KEY
    app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///%s" % DB_NAME
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True

    app.permanent_session_lifetime = timedelta(minutes=5)
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")

    from .DBModels import User

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(u):
        return User.query.get(int(u))

    return app


def create_database(app):
    if not path.exists('WebInterface/' + DB_NAME):
        db.create_all(app=app)
        print("Database created")

WebInterface/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from .DBModels import User
from werkzeug.security import generate_password_hash, check_password_hash
from .DBModels import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route("/login", methods=["POST", "GET"])
def login():
    if request.method == "POST":
        session.permanent = True
        email = request.form.get('email')
        pwd = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if user:
            if check_password_hash(user.password, pwd):
                flash('Logged in successfully', category='sucess')
                login_user(user, remember=True)
                session["user"] = user.email
                return redirect(url_for('views.dashboard'))
            else:
                flash('Incorrect Password, please try again', category='error')
        else:
            flash('Email does not exist', category='error')

    return render_template('login.html', user=current_user)


@auth.route("/logout", methods=["POST", "GET"])
@login_required
def logout():
    logout_user()
    session.pop("user", None)
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    print(request.method)
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists',category='error')
        if len(email) < 4:
            flash('Email must be greater than 4 chars', category='error')
        elif len(first_name) < 2:
            flash('Fairst names must be longer than 2 chars', category='error')
        elif password1 != password2:
            flash('Passwords dont match', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 chars', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            return redirect(url_for('views.dashboard'))

    return render_template('sign_up.html', user=current_user)

WebInterface/views.py
from flask import Blueprint, redirect, render_template, request, flash, jsonify, url_for
from flask_login import login_required, current_user
# from .models import SensorData
from . import db
from .DBModels import db
import json
import os
from .utils import *


PATH = "/Users/sebastiankaeser/Desktop/Coding/Python/Homeserver/JsonData/currentDict.json"

views = Blueprint('views', __name__)


@views.route("/")
def root():
    if current_user.is_authenticated:
        return redirect(url_for("views.dashboard"))
    else:
        return redirect(url_for("auth.login"))


@views.route("/dashboard", methods=["GET", "POST"])
@login_required
def dashboard():
    currentDict = loadJSONDict(PATH)
    s, t, v, l = splitSensorData(currentDict)
    return render_template("index.html", sensors=s, types=t, values=v, l=l)


@views.route("/search", methods=['POST', 'GET'])
def search():
    data = request.form['searchinput']
    return "<h1> %s You want to search lol</h1>" % data


@views.route("/project", methods=['POST', 'GET'])
def project():
    return render_template("project.html")


@views.route("/menu", methods=['POST', 'GET'])
def menu():
    return render_template("menu.html")


@views.route("/settings", methods=['POST', 'GET'])
def settings():
    return render_template("settings.html")

WebInterface/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/global.css')  }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css')  }}">
    {% block head %}{% endblock %}
  </head>
  <body>
      <nav>
        {% block heading %}{% endblock %}
        <ul class='nav-ul'>
            <li><a href="{{ url_for('views.project') }}">Project</a></li>
            <li><a href="{{ url_for('views.menu') }}">Menu</a></li>
            <li><a href="{{ url_for('views.settings') }}">Settings</a></li>
            <form class="searchform" action={{ url_for('views.search') }} method='POST' >
                <input name="searchinput" id="searchinput",class="searchinput"></input>
                <button type="submit" class="search-btn">Search</input>
            </form>

            {% if current_user.is_authenticated %}
              <form method="post" action="{{ url_for('auth.logout') }}">
                  <button type="submit" class="logout-btn btn">Logout</button>
              </form>
            {% else %}
              <form method="get" action="{{ url_for('auth.login') }}">
                  <button type="submit" class="login-btn btn">Login</button>
              </form>
            {% endif %}


        </ul>
      </nav>
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      {% if category == 'error' %}
        <div class="flush bad-flush id="flush">
          {{message}}
          <button>
            <span aria-hidden="true" id="close-btn">&times;</span>
          </button>
        </div>
      {% else %}
        <div class="flush good-flush" id="flush">
         {{message}}
          <button>
            <span aria-hidden="true" id="close-btn">&times;</span>
          </button>
        </div>
      {% endif %}
      {% endfor %}
      {% endif %}
      {% endwith %} 
  {% block body %}{% endblock %}
  </body>
  <script type="text/javascript" src="{{  url_for('static',filename='js/base.js')}}"></script>
</html>

WebInterface/templates/index.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css')  }}">
<title>Dashboard</title>


{% endblock %}





{% block heading %}
<h1 class="heading">Sensors</h1>
{% endblock %}




{% block body %}
<h2>Dashboard</h2>

<div class="maincontainer">

    <div class='sec-sensor'>
        <table>
        <tr>
            <th>Sensor</th>
            <th>Typ</th>
            <th>Wert</th>
        </tr>
        {% for i in range(l) %}
            <tr>
                <th>{{sensors[i]}}</th>
                <th>{{types[i]}}</th>
                <th>{{values[i]}}</th>
            </tr>
        {% endfor %}
        </table>
    </div> 

    <div class='sec-etc'>
        <form action="{{ url_for('views.dashboard') }}" method="post">
            <button type="submit">reload</button>
        </form>
    </div>

</div>



{% endblock %}

WebInterface/templates/login.html
{% extends 'base.html' %}




{% block head %}
<title>Login-Page</title>
{% endblock %}





{% block heading %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css')  }}">
<h1 class="heading">Login</h1>
{% endblock %}





{% block body %}
<h2 class="login-heading">Please Login</h2>
<div class="login-formgroup">
    <form method="post" action="{{ url_for('auth.login') }}">
        <label for="email">Email:</label>
        <input name="email" type="text" placeholder="Enter email"></input>
        <label for="password">Password:</label>
        <input name="password" type="password" placeholder="Enter password"></input>
</div>
<div class="login-button-group">
        <button class="login-form-btn btn" type="submit">Login</button>
    </form>
    <form method="get" action="{{  url_for('auth.sign_up')}}">
        <button class="signup-form-btn btn">Signup</button>
    </form>
</div>
{% endblock %}
   

WebInterface/templates/menu.html
{% extends 'base.html' %}


{% block head %}

{% endblock %}



{% block heading %}

{% endblock %}




{% block body%}
In Work..
{% endblock %}

WebInterface/templates/project.html
{% extends 'base.html' %}


{% block head %}

{% endblock %}



{% block heading %}

{% endblock %}




{% block body%}
in Work..
{% endblock %}

WebInterface/templates/settings.html
{% extends 'base.html' %}



{% block head %}

{% endblock %}



{% block heading %}

{% endblock %}




{% block body%}
In Work..
{% endblock %}

WebInterface/templates/sign_up.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/sign-up.css')  }}">
<title>Sign-Up</title>
{% endblock %}



{% block heading %}
<h1 class="heading">Sign-Up</h1>
{% endblock %}





{% block body %}
<h2 class="signup-heading">Register for new Account </h2>
<div class="signup-formgroup">
    <form method="post" action="{{ url_for('auth.sign_up') }}">
        <label for="email">Email:</label>
        <input name="email" type="text" placeholder="email"></input>
        <label for="firstName">First Name:</label>
        <input name="firstName" type="text" placeholder="first name"></input>
        <label for="password1">Password</label>
        <input name="password1" type="password1" placeholder="password"></input>
        <label for="password2">Passwordd</label>
        <input name="password2" type="password2" placeholder="password"></input>
        <button class="signup-btn btn" type="submit">SUBMIT</button>
</div>
    <form>
{% endblock %}
   